apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  volumes:
    #creating a shared volume and will mount it to both the pods
  - name: shared-data
    emptyDir: {}
  containers:
  - name: web-container
    image: nginx
    volumeMounts: 
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: ftp-container
    image: fauria/vsftpd
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    env:
    - name: FTP_USER
      value: admin
    - name: FTP_PASS
      value: password

#kubectl exec -it multi -c ftp-container  -- /bin/bash
#kubectl exec -it multi -c web-container  -- /bin/bash